(()=>{'use strict';if(window.CosmicRooms)return;const API=location.hostname.endsWith('.github.io')?'https://cosmicv2.v75ultimate.workers.dev':location.origin;const KEY='cosmicRoomSessionV1';const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){return null}};const save=x=>{try{x?localStorage.setItem(KEY,JSON.stringify(x)):localStorage.removeItem(KEY)}catch(_){}};
const playerName=()=>{try{return localStorage.getItem('cosmicCurrentUserV1')||'Guest'}catch(_){return'Guest'}};const playerId=()=>{let p=load();if(p?.playerId)return p.playerId;const id='p-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);save({playerId:id,playerName:playerName()});return id};
async function request(code,action='get',room,player){const r=await fetch(API+'/api/rooms/'+encodeURIComponent(code),{method:action==='get'?'GET':'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:action==='get'?undefined:JSON.stringify({action,room,player})});const d=await r.json().catch(()=>({ok:false,error:'invalid-response'}));if(!r.ok||d.ok===false)throw new Error(d.error||'Room request failed');return d}
async function create(name,code){const p={id:playerId(),name:playerName()};const d=await request(code,'create',{name},p);save({playerId:p.id,playerName:p.name,code,isHost:true});return d}
async function join(code){const p={id:playerId(),name:playerName()};const d=await request(code,'join',null,p);save({playerId:p.id,playerName:p.name,code,isHost:String(d.room?.host)===String(p.id)});return d}
async function leave(){const p=load();if(!p?.code)return {ok:true,room:null};try{const d=await request(p.code,'leave',null,{id:p.playerId,name:p.playerName});save(null);return d}catch(e){save(null);throw e}}
async function get(code){return request(code,'get')}
async function current(){const p=load();if(!p?.code)return null;try{const d=await get(p.code);if(!d.room){save(null);return null}return {...d.room,session:p}}catch(_){return null}}
async function update(room){const p=load();if(!p?.code)throw new Error('Not in a room');return request(p.code,'update',room,{id:p.playerId,name:p.playerName})}
window.CosmicRooms={create,join,leave,get,current,update,session:load};})();