(() => {
  'use strict';
  const ADMIN='TheDevilAngel',SESSION='cosmicCurrentUserV1',BASE=location.hostname.endsWith('.github.io')?'/cosmic/':'/',WORKER='https://cosmicv2.v75ultimate.workers.dev';
  const user=()=>{try{return localStorage.getItem(SESSION)||'Guest'}catch(_){return 'Guest'}};
  if(user()!==ADMIN){location.replace(BASE+'pages/lessons/lessons.html');return}
  const safe=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const allowed=new Set(['Arcade','Multiplayer','Puzzle','Utility','AI','New']);
  const get=async u=>{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(r.status);return r.json()};const el=id=>document.getElementById(id);let issues=[],stats={};
  function row(kind,name,status,detail){return '<div class="doctor-row '+(status==='OK'?'ok':status==='WARN'?'warn':'bad')+'"><div><b>'+safe(name)+'</b><small>'+safe(kind)+'</small></div><strong>'+safe(status)+'</strong><p>'+safe(detail)+'</p></div>'}
  async function inspectRegistry(label,url,kind){const data=await get(url);if(!Array.isArray(data))throw new Error(label+' registry is not an array');const seen=new Map();for(const item of data){const name=String(item?.name||'').trim();if(!name){issues.push(row(kind,'Unnamed item','BAD','Missing name.'));continue}const key=name.toLowerCase();if(seen.has(key))issues.push(row(kind,name,'BAD','Duplicate name; conflicts with another registry item.'));else seen.set(key,true);if(!item.category||!allowed.has(String(item.category)))issues.push(row(kind,name,'WARN','Invalid or unknown category: '+String(item.category||'(missing)')));const path=String(item.path||'').trim();if(!path){issues.push(row(kind,name,'BAD','Missing path.'));continue}if(/^https?:\\/\\//i.test(path))continue;const entry=String(item.entry||'index.html');const target=BASE+path.replace(/^\\.\\//,'')+entry;const status=await fetch(target,{method:'HEAD',cache:'no-store'}).then(r=>r.ok?'OK':'BAD').catch(()=> 'BAD');if(status!=='OK')issues.push(row(kind,name,'BAD','Entry file could not be reached: '+target));if(item.image){const image=BASE+String(item.image).replace(/^\\.\\//,'');const ok=await fetch(image,{method:'HEAD',cache:'no-store'}).then(r=>r.ok).catch(()=>false);if(!ok)issues.push(row(kind,name,'BAD','Image/asset could not be reached: '+image));}}stats[label]=data.length;return data}
  async function run(){issues=[];stats={};renderState('Running checks…');try{const [games,apps]=await Promise.all([inspectRegistry('Games',BASE+'pages/lessons/games.json','Game'),inspectRegistry('Apps',BASE+'apps/apps.json','App')]);const names=new Map();for(const {x,kind} of [...games.map(x=>({x,kind:'game'})),...apps.map(x=>({x,kind:'app'}))]){const key=String(x.name||'').trim().toLowerCase();if(!key)continue;if(names.has(key))issues.push(row(kind,x.name,'BAD','Duplicate name across games/apps registry.'));else names.set(key,true)}const api=await fetch(WORKER+'/api/hub-diagnostics',{cache:'no-store'}).then(r=>r.json()).catch(()=>null);if(api?.assets)stats.worker=Object.values(api.assets).filter(x=>x.status>=200&&x.status<300).length+'/'+Object.keys(api.assets).length;renderSummary()}catch(e){issues=[row('Doctor','Registry','BAD',e.message||String(e))];renderSummary()}}
  function renderState(text){el('doctor-summary').innerHTML='<div class="doctor-summary-card">'+safe(text)+'</div>';el('doctor-results').innerHTML=''}
  function renderSummary(){const bad=issues.filter(x=>/class="doctor-row bad"/.test(x)).length,warn=issues.filter(x=>/class="doctor-row warn"/.test(x)).length;el('doctor-summary').innerHTML='<div class="doctor-stats"><div><b>'+Object.values(stats).reduce((a,b)=>a+(Number(b)||0),0)+'</b><span>registry items</span></div><div><b>'+bad+'</b><span>errors</span></div><div><b>'+warn+'</b><span>warnings</span></div><div><b>'+safe(stats.worker||'n/a')+'</b><span>worker checks</span></div></div>';el('doctor-results').innerHTML=issues.length?issues.join(''):'<div class="doctor-clean"><b>All checks passed.</b><span>No broken paths, duplicate names, or invalid local entries were found.</span></div>'}
  el('doctor-run').onclick=run;el('doctor-export').onclick=()=>{const text='Cosmic Doctor report\\nUser: '+user()+'\\nTime: '+new Date().toISOString()+'\\nIssues: '+issues.length+'\\n';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download='cosmic-doctor-report.txt';a.click()};run();
})();