(() => {
'use strict';
if(window.__COSMIC_SPACES__)return;window.__COSMIC_SPACES__=true;
const css=document.createElement('style');css.textContent=`
#cosmic-spaces{position:fixed;inset:0;z-index:2147483000;background:rgba(2,7,12,.96);display:none;color:#eefaff;font:14px system-ui,sans-serif}
#cosmic-spaces.show{display:block}.cs-top{height:46px;display:flex;align-items:center;gap:8px;padding:0 10px;border-bottom:1px solid #163545;background:#06131c}
.cs-title{font-weight:900;color:#62dcff;margin-right:auto}.cs-btn{border:1px solid #22566b;background:#091e2a;color:#bceeff;border-radius:8px;padding:6px 9px;cursor:pointer}.cs-dock{position:absolute;left:0;right:0;bottom:0;height:48px;display:flex;gap:6px;padding:6px 9px;background:#06131c;border-top:1px solid #163545;overflow:auto}.cs-win{position:absolute;border:1px solid #2dccff;border-radius:10px;background:#02090f;box-shadow:0 18px 50px #000;overflow:hidden;resize:both;min-width:260px;min-height:180px}.cs-head{height:34px;display:flex;align-items:center;padding:0 7px;background:#081b25;cursor:move}.cs-name{font-weight:800;font-size:12px;margin-right:auto}.cs-frame{width:100%;height:calc(100% - 34px);border:0;background:#000}
`;document.head.appendChild(css);
function boot(){let root=document.getElementById('cosmic-spaces');if(!root){root=document.createElement('div');root.id='cosmic-spaces';document.body.appendChild(root)}render()}
function render(){const root=document.getElementById('cosmic-spaces'),s=CosmicRuntime.load();root.innerHTML='<div class="cs-top"><span class="cs-title">Cosmic Spaces</span><button class="cs-btn" id="cs-close">Close</button></div>';s.items.filter(x=>!x.minimized).forEach((x,i)=>{const w=document.createElement('section');w.className='cs-win';w.dataset.id=x.id;w.style.left=(x.x||60)+'px';w.style.top=(x.y||70)+'px';w.style.width=(x.w||720)+'px';w.style.height=(x.h||480)+'px';w.innerHTML='<div class="cs-head"><span class="cs-name"></span><button class="cs-btn" data-min>—</button><button class="cs-btn" data-close>×</button></div><iframe class="cs-frame" allow="fullscreen"></iframe>';w.querySelector('.cs-name').textContent=x.name;w.querySelector('.cs-frame').src=x.url;w.querySelector('[data-close]').onclick=()=>{CosmicRuntime.close(x.id);render()};w.querySelector('[data-min]').onclick=()=>{CosmicRuntime.minimize(x.id,true);render()};w.querySelector('.cs-head').ondblclick=()=>{CosmicRuntime.activate(x.id);};root.appendChild(w)});const dock=document.createElement('div');dock.className='cs-dock';s.items.forEach(x=>{const b=document.createElement('button');b.className='cs-btn';b.textContent=x.name;b.onclick=()=>{CosmicRuntime.activate(x.id);render()};dock.appendChild(b)});root.appendChild(dock);root.querySelector('#cs-close').onclick=()=>root.classList.remove('show')}
window.CosmicSpaces={open:x=>{CosmicRuntime.open(x);document.getElementById('cosmic-spaces')?.classList.add('show');render()},show:()=>{document.getElementById('cosmic-spaces')?.classList.add('show');render()},hide:()=>document.getElementById('cosmic-spaces')?.classList.remove('show')};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();