#!/usr/bin/env python3
"""Sync the private gfiles game catalog into Cosmic without copying game files."""

from __future__ import annotations

import json
import re
import subprocess
import sys
import urllib.parse
from pathlib import Path

REGISTRY = Path("pages/lessons/games.json")
SOURCES = [
    ("gfiles", "Ultimate-Guy/gfiles"),
    ("gfiles2", "Ultimate-Guy/gfiles2"),
    ("gfiles3", "Ultimate-Guy/gfiles3"),
    ("gfiles4", "Ultimate-Guy/gfiles4"),
    ("gfiles5", "Ultimate-Guy/gfiles5"),
]
EXCLUDED = {".git", ".github", "patch", "build", "frame", "warning",
            "warnings", "404", "408", "offline"}


def norm(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.casefold())


def display_name(folder: str) -> str:
    value = re.sub(r"([a-z])([A-Z])", r"\1 \2", folder)
    value = re.sub(r"[_-]+", " ", value).strip()
    value = re.sub(r"\s+", " ", value)
    return value.title() or folder


def tree(repo: str) -> dict:
    result = subprocess.run(
        ["gh", "api", f"/repos/{repo}/git/trees/main?recursive=1"],
        check=True,
        text=True,
        capture_output=True,
    )
    data = json.loads(result.stdout)
    if data.get("truncated"):
        raise SystemExit(f"{repo}: GitHub returned a truncated tree")
    return data


def main() -> int:
    if not REGISTRY.is_file():
        raise SystemExit(f"Missing {REGISTRY}")

    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise SystemExit("games.json must contain an array")

    # Remove only entries previously generated by this importer.
    data = [
        item for item in data
        if not (
            str(item.get("source", "")).casefold() in {s[0] for s in SOURCES}
            or str(item.get("path", "")).startswith("gfiles/")
        )
    ]

    seen = {norm(str(item.get("name", ""))) for item in data}
    added = 0
    duplicate_count = 0
    source_counts = {}

    for source_id, repo in SOURCES:
        source_added = 0
        folders = set()

        for entry in tree(repo).get("tree", []):
            path = str(entry.get("path", ""))
            parts = path.split("/")
            if entry.get("type") != "blob" or len(parts) != 2:
                continue
            if parts[1].casefold() != "index.html":
                continue

            folder = parts[0]
            if folder.casefold() in EXCLUDED or folder in folders:
                continue
            folders.add(folder)

            name = display_name(folder)
            key = norm(name)
            if not key or key in seen:
                duplicate_count += 1
                continue

            data.append({
                "name": name,
                "path": f"gfiles/{source_id}/{urllib.parse.quote(folder, safe='')}/index.html",
                "category": "Arcade",
                "tags": ["gfiles"],
                "featured": False,
                "source": source_id,
                "source_path": f"{folder}/index.html",
            })
            seen.add(key)
            added += 1
            source_added += 1

        source_counts[source_id] = source_added

    data.sort(key=lambda item: (
        1 if str(item.get("source", "")) in {s[0] for s in SOURCES} else 0,
        norm(str(item.get("name", ""))),
        str(item.get("path", "")),
    ))
    REGISTRY.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    print("PRIVATE GFILES CATALOG SYNC")
    print("===========================")
    for source_id, count in source_counts.items():
        print(f"{source_id}: +{count}")
    print(f"added: {added}")
    print(f"duplicates skipped: {duplicate_count}")
    print(f"final registry entries: {len(data)}")
    print("game files copied into Cosmic: 0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
